name: ReVanced Build

on:
  workflow_dispatch:

jobs:
  build:
    # name: Patch Revanced
    permissions: write
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Download APKs from APKMirror
        run:  ./scripts/download.sh -r

      - name: Build APKs
        run:  ./scripts/build.sh 
              
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        with:
          releaseDirectory: build
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          output: build/release/signed
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
        env:
          BUILD_TOOLS_VERSION: "33.0.0"   
          
      # - name: Rename APK file
      #   run: ./scripts/rename-updater.sh
          
      - name: Generate SHA256 checksums for the signed APK file
        run: ./scripts/sha256gen.sh -r
      
      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: "${{ env.date_now_nodashes }}-yt"
          # title: "ReVanced ${{ env.date_now }}"
          # prerelease: false
          automatic_release_tag: "latest"
          draft: true
          title: "Release ${{ env.date_now }}"
          files: |
            build/SHA-256-yt.txt
            build/*.apk
            vanced-microG.apk
