name: ReVanced

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download base APK
        run: ./scripts/download.sh -r

      - name: Build APK
        run: ./scripts/build.sh -r
              
      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV && echo "date_now_nodashes=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        with:
          releaseDirectory: build
          signingKeyBase64: '${{ secrets.SIGNING_KEY }}'
          output: build/release/signed
          alias: '${{ secrets.ALIAS }}'
          keyStorePassword: '${{ secrets.KEY_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.KEY_PASSWORD }}'
        env:
          BUILD_TOOLS_VERSION: "33.0.0"     
          
      - name: Generate SHA256 checksums for the signed APK file
        run: ./scripts/sha256gen.sh -r
        
      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v2
        run: echo "{name}={value}" >> $GITHUB_STATE
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: marvinpinto/action-automatic-releases@latest
        name: Release ReVanced
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.date_now_nodashes }}-yt"
          title: "ReVanced ${{ env.date_now }}"
          prerelease: false
          files: |
            build/SHA-256-yt.txt
            build/revanced-nonroot-signed.apk
            vanced-microG.apk
